# Generated by Django 5.2.5 on 2025-08-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_names', models.CharField(max_length=45)),
                ('last_names', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
