# Generated by Django 5.2.5 on 2025-08-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payslip_reportcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('valid', 'valid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=10)),
                ('day', models.DateField(auto_now_add=True)),
                ('Payslip_Reportcard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payslip_reportcard.payslip_reportcard')),
            ],
        ),
    ]
