# Generated by Django 5.2.5 on 2025-08-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip_Reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
                ('year', models.PositiveSmallIntegerField()),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payslip.payslip')),
            ],
        ),
    ]
