# Generated by Django 5.2.5 on 2025-08-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('mission_leave', 'mission_leave')], default='Present', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
